# Site Info
title: "MultifokalHirn"
description: "Personal Website of MultifokalHirn"
# google_verify: abc123 # Put your Google Verification here
# google_analytics: UA-123

# Author Info
author_name: "Lennard Wolf" # Your name here
# author_email: ? # Your email here
author_gravatar: aa4d7d1621a82415168ad023db78c870 # Your Gravatar md5 hash here for logo

# Site Settings
url: https://multifokalhirn.github.io # Change to your site
remote_theme: aterenin/minima-reboot

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

# base_url: /gh-pages-minima-starter # TODO: ?
repository: MultifokalHirn/multifokalhirn.github.io

# Minima social links
github_username: MultifokalHirn
linkedin_username: lennardwolf
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

exclude:
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
