# Site Info
title: "Lennard Wolf's Homepage"
description: "Lennard Wolf's Homepage"
# google_verify: abc123 # Put your Google Verification here
# google_analytics: UA-123

# Author Info
author_name: "Lennard Wolf" # Your name here
author: "Lennard Wolf" # Your name here
# author_email: ? # Your email here
author_gravatar: aa4d7d1621a82415168ad023db78c870 # Your Gravatar md5 hash here for logo

# Site Settings
url: https://multifokalhirn.github.io
remote_theme: aterenin/minima-reboot

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - tag-page-generator
  - jekyll-minifier
  # - faraday-retry
sass:
  sass_dir: _sass
  style: compact

repository: MultifokalHirn/multifokalhirn.github.io

# Minima: show excerpts in the frontpage
show_excerpts: true

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

collections:
  tags:
    output: true
    permalink: tags/:path/

# # Generate social links in footer. to add icons go to https://github.com/jekyll/minima/tree/master/_includes/social-icons
# social_links:
#   - { platform: "github", user_url: "https://github.com/MultifokalHirn" }
#   # - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
#   # - {
#   #     platform: "linkedin",
#   #     user_url: "https://www.linkedin.com/in/lennardwolf",
#   #   }
#   # - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# footer_icons:
#   - { icon: "github", url: "https://github.com/MultifokalHirn" }
#   # - { icon: "linkedin", url: "https://www.linkedin.com/in/lennardwolf" }
#   # - { icon: instagram,      user_url: "https://www.instagram.com/jekyll" }
#   # - { icon: youtube,        user_url: "https://www.youtube.com/jekyll" }

header_pages:
  - _pages/about.md
  - _pages/resume.md
  - _pages/posts.md
  - _pages/github.md
  - _pages/linkedin.md

include:
  - _pages
  - _posts

exclude:
  - _post-drafts
  - .gitignore
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md

jekyll-minifier:
  preserve_php: false # Default: false
  remove_spaces_inside_tags: true # Default: true
  remove_multi_spaces: true # Default: true
  remove_comments: true # Default: true
  remove_intertag_spaces: true # Default: false
  remove_quotes: false # Default: false
  compress_css: true # Default: true
  compress_javascript: true # Default: true
  compress_json: true # Default: true
  simple_doctype: false # Default: false
  remove_script_attributes: false # Default: false
  remove_style_attributes: false # Default: false
  remove_link_attributes: false # Default: false
  remove_form_attributes: false # Default: false
  remove_input_attributes: false # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false # Default: false
  remove_https_protocol: false # Default: false
  preserve_line_breaks: true # Default: false
  simple_boolean_attributes: false # Default: false
  compress_js_templates: false # Default: false
  preserve_patterns: # Default: (empty)
  uglifier_args: # Default: (empty)
